import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { ViewTransitions } from "next-view-transitions";
import { NetworkProvider } from "@/providers/network-provider";
import ReactQueryProvider from "@/providers/react-query-provider";
import { Toaster } from "sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ViewTransitions>
			<html lang="en" suppressHydrationWarning>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<NetworkProvider>
							<ReactQueryProvider>
								{children}
								<Toaster position="top-right" richColors closeButton />
							</ReactQueryProvider>
						</NetworkProvider>
					</ThemeProvider>
				</body>
			</html>
		</ViewTransitions>
	);
}
